# Generated by Django 5.2.8 on 2025-12-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dueno', models.CharField(max_length=100, verbose_name='Nombre del dueno')),
                ('mascota', models.CharField(max_length=100, verbose_name='Nombre de la mascota')),
                ('especie', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('peso', models.FloatField()),
                ('unidad_peso', models.CharField(choices=[('k', 'Kilogramos'), ('g', 'Gramos')], default='k', max_length=1)),
                ('esterilizado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
